# Generated by Django 4.0.6 on 2022-07-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(default='admin', max_length=30, verbose_name='login'),
        ),
    ]
