# Generated by Django 4.0.6 on 2022-08-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_team_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_status',
            field=models.BooleanField(default=False),
        ),
    ]
