# Generated by Django 4.0.6 on 2022-08-02 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_appointment_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='admin_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='worker',
            field=models.ForeignKey(blank=True, limit_choices_to={'admin_status': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_name', to='base.team'),
        ),
    ]
