# Generated by Django 4.0.6 on 2022-07-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=60, null=True, verbose_name='last_name')),
                ('phone', models.IntegerField(max_length=12, null=True, verbose_name='phone')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
