# Generated by Django 4.0.6 on 2022-08-02 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_user_admin_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=30)),
                ('date_time', models.DateTimeField(max_length=30)),
                ('service', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='base.user')),
                ('employee', models.ForeignKey(limit_choices_to={'admin_status': True}, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='base.user')),
            ],
        ),
    ]
